name: CI

on: workflow_dispatch

# on:
  # push:
    # branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: privapps/docker-ttskit@main
        with:
          text: '1'
          content: './out.wav'
      - run: ls -l
