name: CI

on: workflow_dispatch

# on:
  # push:
    # branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: TTSKIT
        uses: privapps/docker-ttskit@0.1.0
      # - uses: privapps/docker-ttskit@main
        with:
          text: '请通行'
          content: './pass.wav'
      - run: ls -l
